
version: "3"

services:
  web:
    build:
      context: ./test-stori
      dockerfile: dockerfile
    depends_on:
      - app
    ports:
      - "3001:3000"

  app:
    build:
      context: ./pruebaTecnica
      dockerfile: dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: mongo




